services:
  xrcultureviewer:
    image: svilenvarbanov2019/xrcultureviewer:latest
    ports:
      - "6130:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - xrculture_data:/xrculture/viewer
    restart: unless-stopped

volumes:
  xrculture_data: