FROM svilenvarbanov2019/openmvg-openmvs:latest

RUN apt-get update && \
  apt-get install -y aspnetcore-runtime-8.0

WORKDIR /app

# Expects the Release publish output to be available
COPY ./XRCulture3DReconstruction/bin/Release/net8.0/publish/ .

# OBJ2BIN
COPY ./Linux/obj2bin /usr/local/bin

EXPOSE 8080

ENTRYPOINT ["dotnet", "XRCulture3DReconstruction.dll"]